version: '3.6'

networks:
  web-app:
    name: web-app_default
    external: true

services:
  mongodb:
    container_name: mongodb_cryptobalancebot
    image: mongo:5.0.5
    restart: always
    expose:
      - 27017
    volumes:
      - ${DB_DATA_DIR}:/data/db

  telebot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CMD_NAME=telebot
    container_name: telebot_cryptobalancebot
    image: telebot
    environment:
      - CONFIG_DIR=${CONFIG_DIR}
    volumes:
      - $CONFIG_DIR:/cryptobalancebot
  
  observer:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - CMD_NAME=observer
    container_name: observer_cryptobalancebot
    image: observer
    environment:
      - CONFIG_DIR=${CONFIG_DIR}
    volumes:
      - $CONFIG_DIR:/cryptobalancebot
    networks:
      - web-app

  resource:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CMD_NAME=resource
    container_name: resource_cryptobalancebot
    image: resource
    environment:
      - CONFIG_DIR=${CONFIG_DIR}
    volumes:
      - $CONFIG_DIR:/cryptobalancebot
    ports:
      - ${RESOURCE_PORT}:1234
