version: '3.6'

services:
  mongodb:
    container_name: mongodb_cryptobalancebot
    image: mongo:5.0.5
    restart: always
    expose:
      - 27017
    volumes:
      - ${DB_DATA_DIR}:/data/db

  telebot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CMD_NAME=telebot
    container_name: telebot_cryptobalancebot
    image: telebot
    environment:
      - CONFIG_DIR=${CONFIG_DIR}
    volumes:
      - $CONFIG_DIR:/cryptobalancebot
  
  observer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CMD_NAME=observer
    container_name: observer_cryptobalancebot
    image: observer
    environment:
      - CONFIG_DIR=${CONFIG_DIR}
    volumes:
      - $CONFIG_DIR:/cryptobalancebot

  resource:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CMD_NAME=resource
    container_name: resource_cryptobalancebot
    image: resource
    environment:
      - CONFIG_DIR=${CONFIG_DIR}
    volumes:
      - $CONFIG_DIR:/cryptobalancebot
    ports:
      - ${RESOURCE_PORT}:1234
