version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: app-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL
      - JWT_SECRET
      - JWT_EXPIRATION
    depends_on:
      - db
    command:
      - |
        npx prisma db push
        node /app/dist/main.js

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: app-frontend
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
      - BACKEND_URL
      - SESSION_SECRET_KEY
    depends_on:
      - backend
      - db

  db:
    container_name: mongodb_cryptobalancebot
    image: mongo:5.0.5
    restart: always
    ports:
      - '27017:27017'
    expose:
      - 27017
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongosh --quiet) -eq 1
      interval: 10s
      start_period: 30s
    # volumes:
    #   - ${DB_DATA_DIR}:/data/db

volumes:
  db_data:
